script for running on windows
ChrisMisan/TK pull request #1
Opened 2022-05-23 15:31 UTC by KrzysztofCzech

python run_app.py -> script for building and starting app
run_client.bat -> script for starting without generating files

2022-05-24 10:16 UTC, ChrisMisan requested changes
I tested this on win10 and it worked just fine but I'd like to have the changes from #2 included in run_app.py

2022-05-25 09:03 UTC, KrzysztofCzech commented
Deleted call of build.sh in run_app.py as it is already included in start.sh

2022-05-25 11:10 UTC, ChrisMisan commented
Now it looks just fine.

2022-05-25 11:10 UTC, ChrisMisan approved these changes

2022-05-25 21:16 UTC, merged